//Insert package name
package com.mycompany.skills.demo;

// imports
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class AddMember extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddMember.class.getName());

    /**
     * Creates new form AddMember
     */
    public AddMember(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MemberIDText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        NameText = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        EmailText = new javax.swing.JTextArea();
        MemberCombo = new javax.swing.JComboBox<>();
        AMbtn1 = new javax.swing.JButton();
        AMbtn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Member");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("Member ID:");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel4.setText("Member Type:");

        MemberIDText.setColumns(20);
        MemberIDText.setRows(5);
        jScrollPane1.setViewportView(MemberIDText);

        NameText.setColumns(20);
        NameText.setRows(5);
        jScrollPane2.setViewportView(NameText);

        EmailText.setColumns(20);
        EmailText.setRows(5);
        jScrollPane3.setViewportView(EmailText);

        MemberCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Staff" }));

        AMbtn1.setText("OK");
        AMbtn1.addActionListener(this::AMbtn1ActionPerformed);

        AMbtn2.setText("Cancel");
        AMbtn2.addActionListener(this::AMbtn2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3)
                            .addComponent(MemberCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(AMbtn1)
                        .addGap(56, 56, 56)
                        .addComponent(AMbtn2)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MemberCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AMbtn1)
                    .addComponent(AMbtn2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AMbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMbtn1ActionPerformed
   
    // Check all fields are filled, or else user wont be able to continue
    if (MemberIDText.getText().isBlank() ||
        NameText.getText().isBlank() ||
        EmailText.getText().isBlank()) {
        
        JOptionPane.showMessageDialog(this, "Please fill in all fields!!!!");
        return; // stops here, keeps the form open, the user can then exit with the cancel button :)
    }

    // If the email field doesnt contain a @, or valid email adress, it lets the user know
    if (!EmailText.getText().contains("@")) {
        System.out.println("Invalid email: missing @ symbol.");
    }
    
    // If the user enters anything other than an int into the member ID field
    // a message appears telling them to input integer values instead
    // using the try catch method 

    try {
        int memberID = Integer.parseInt(MemberIDText.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid Member ID: Please use only integers, and try again.");
        return; // keeps the form open
    } 

        submitted = true;
        dispose();   
    }//GEN-LAST:event_AMbtn1ActionPerformed

    private void AMbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMbtn2ActionPerformed
    // Exits the AddMember form
        dispose();
    }//GEN-LAST:event_AMbtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddMember dialog = new AddMember(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // adding getters to extract data user inputs into the text fields 
    // when ok button clicked 

    public int getMemberID() {
        return Integer.parseInt(NameText.getText());
    }

    public String getName() {
        return NameText.getText();
    }

    public String getEmail() {  
        return EmailText.getText();
    }

    public String getMemberType() {
        // Combo box info to string
        return MemberCombo.getSelectedItem().toString();
    }    
    
    // Sets submit button to true
    private boolean submitted = false;

    public boolean wasSubmitted() { return submitted; }

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {
        submitted = true;
        dispose();
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AMbtn1;
    private javax.swing.JButton AMbtn2;
    private javax.swing.JTextArea EmailText;
    private javax.swing.JComboBox<String> MemberCombo;
    private javax.swing.JTextArea MemberIDText;
    private javax.swing.JTextArea NameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
