/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

//Insert package name
package com.mycompany.skills.demo;

// imports
import java.util.ArrayList;

/**
 *
 * @author 
 */
    /**
     * Creates new form BorrowBook
     */
    public class BorrowBook extends javax.swing.JDialog {

        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BorrowBook.class.getName());

        // Constructor - accepts the parent window and the book list from JFrame
        public BorrowBook(java.awt.Window parent, boolean modal, ArrayList<Book> bookList) {
            super((java.awt.Frame) parent, modal);
            initComponents();

            // Clear the default placeholder items (Item 1, Item 2 etc.)
            BB_Combo.removeAllItems();

            // Populate the combo box with books from the list passed in from JFrame
            for (Book b : bookList) {
                BB_Combo.addItem(b.getItemID() + " - " + b.getTitle());
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // Returns true if the user clicked the OK button, false if they cancelled
    public boolean wasSubmitted() {
        return submitted;
    }

    // Returns the user selected item from the combo box
    // This will be a string in the format "BookID - Title" btw guys :)
    public String getSelectedBookItem() {
        return (String) BB_Combo.getSelectedItem();
    } 
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BB_Combo = new javax.swing.JComboBox<>();
        BB_Btn1 = new javax.swing.JButton();
        BB_Btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Borrow a book");

        BB_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BB_Combo.addActionListener(this::BB_ComboActionPerformed);

        BB_Btn1.setText("OK");
        BB_Btn1.addActionListener(this::BB_Btn1ActionPerformed);

        BB_Btn2.setText("Cancel");
        BB_Btn2.addActionListener(this::BB_Btn2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(BB_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(BB_Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BB_Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BB_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BB_Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BB_Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BB_Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BB_Btn1ActionPerformed
        // Once users clicks the ok button the window closes
        submitted = true;
        dispose();           
    }//GEN-LAST:event_BB_Btn1ActionPerformed

    private void BB_Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BB_Btn2ActionPerformed
        // Closes the BorrowBook dialog form
        dispose();
    }//GEN-LAST:event_BB_Btn2ActionPerformed

    private void BB_ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BB_ComboActionPerformed

    }//GEN-LAST:event_BB_ComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                BorrowBook dialog = new BorrowBook(new javax.swing.JFrame(), true, new java.util.ArrayList<>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Boolean to check if the user clicks
    // OK or cancel, defaults to false until button is pressed 
    // which makes it true 
    private boolean submitted = false;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BB_Btn1;
    private javax.swing.JButton BB_Btn2;
    private javax.swing.JComboBox<String> BB_Combo;
    // End of variables declaration//GEN-END:variables
}
