//Insert package name
package com.mycompany.skills.demo ;

/**
 *
 * @author 
 */

// imports
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class JFrame extends javax.swing.JFrame {    
    // array list containing member IDs
    private ArrayList<Member> memberList = new ArrayList<>();
    
    // array list containing books 
    private ArrayList<Book> bookList = new ArrayList<>();
    
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Smart Library Management System");

        Btn1.setText("Add Member");
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn2.setText("Add Book");
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        Btn3.setText("Borrow Book");
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });

        Btn4.setText("Return Book");
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });

        Btn5.setText("Exit Program");
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(Btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        // When button 2 is pressed it opens the AddBook
        // which the user must close to get back to the main menu 
        AddBook dialog = new AddBook(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        
        // Event handler that processes user input from the AddBook form
        // which is later stored in an array list containing books 
        if (dialog.wasSubmitted()) {
            String title = dialog.getTitle();
            int itemID = dialog.getBookID();
            String author = dialog.getAuthor();
            int isbn = dialog.getISBN();     
        
        // Creates a new Book object using the details from the form
        // then adds newly created book to list
        Book newBook = new Book(title, itemID, author, isbn); 
        bookList.add(newBook);
        }
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        // When Btn1 is pressed (The one that says add member) it
        // pulls up the AddMember dialog windowS
        AddMember dialog = new AddMember(this, true); // true = modal
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        
        // Event handler that processes user input from the AddMember form
        // that is later saved to an array list
        if (dialog.wasSubmitted()) {
            int memberID = dialog.getMemberID();
            String name = dialog.getName();
            String email = dialog.getEmail();
            String type = dialog.getMemberType();

            Member newMember = null;
            
            // if statement that checks if a new member is staff or student 
            if (type.equals("Student")) {
                newMember = new StudentMember(memberID, name, email, 0);
            } else {
                newMember = new StaffMember(memberID, name, email, 0);
            }
            
            // adds member to array list 
            memberList.add(newMember);
        }    
        // newMember is ready to use, e.g. add to a list        
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        // Open the BorrowBox dialog, passing in the book list
        // so the combo box can display all available books :P
        BorrowBook dialog = new BorrowBook(this, true, bookList); // true = modal
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        
        // Only process the selection if the user clicked OK, not Cancel
        if (dialog.wasSubmitted()) {

            // Get selected string from combo box e.g. "A001 - The Flower Book"
            String selectedBook = dialog.getSelectedBookItem();

            // Extract the itemID from before the " - "
            String selectedID = selectedBook.split(" - ")[0];

            // Loop through the book list to find the matching book
            for (Book b : bookList) {
                if (b.getItemID().equals(selectedID)) {

                    // Check if the book is already borrowed before proceeding
                    // there's also text that lets the user know if the book was 
                    // successfully borrowed or noty
                    if (b.isBorrowed()) {
                        JOptionPane.showMessageDialog(this, 
                            "This book is already borrowed!");
                    } else {
                        // Mark the book as borrowwwed
                        b.setBorrowed(true);
                        JOptionPane.showMessageDialog(this, 
                            "Book borrowed successfully!");
                    }
                    break; // stop looping once the matching book is found
                }
            }
        }
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
    
    // Open the ReturnBook dialog, passing in the book list
    ReturnBook dialog = new ReturnBook(this, true, bookList);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);

    // Only process if the user clicked OK, not Cancel
    if (dialog.wasSubmitted()) {

        // Get the selected book string e.g. "A001 - The Flower Book"
        String selectedBook = dialog.getSelectedBookItem();

        // Extract the itemID from before the " - "
        String selectedID = selectedBook.split(" - ")[0];

        // Loop through book list to find the matching book
        for (Book b : bookList) {
            if (b.getItemID().equals(selectedID)) {

                // Mark the book as no longer borrowed
                b.setBorrowed(false);
                JOptionPane.showMessageDialog(this,
                    "Book returned successfully!");
                break; // stop looping once the matching book is found
            }
        }
    }

    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
        // Closing the smart library management system menu
        // when button clicked
        dispose();
    }//GEN-LAST:event_Btn5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
