/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

// package
package com.mycompany.skills.demo;

// imports
import java.util.ArrayList;

/**
 *
 * @author MushyMelon
 */
public class ReturnBook extends javax.swing.JDialog {
    
    // Boolean flag - true if user clicks OK, false if cancelled :/
    private boolean submitted = false;

    // Returns true if user clicked OK for ref
    public boolean wasSubmitted() {
        return submitted;
    }

    // Returns the selected item from the combo box in the format "itemID - Title", just so you guys know
    public String getSelectedBookItem() {
        return (String) RB_Combo.getSelectedItem();
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReturnBook.class.getName());

    /**
     * Creates new form ReturnBook
     */
// Constructor - accepts the parent window and the book list from JFrame
// Only shows books that are currently borrowed, since you can only return borrowed books
    public ReturnBook(java.awt.Window parent, boolean modal, ArrayList<Book> bookList) {
        super((java.awt.Frame) parent, modal);
        initComponents();

        // Clear the default placeholder items (Item 1, Item 2 etc.)
        RB_Combo.removeAllItems();

        // Only add books that are currently borrowed to the combo box
        for (Book b : bookList) {
            if (b.isBorrowed()) {
                RB_Combo.addItem(b.getItemID() + " - " + b.getTitle());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RB_Combo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        RB_Btn1 = new javax.swing.JButton();
        RB_Btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rerurn Book");

        RB_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        RB_Combo.addActionListener(this::RB_ComboActionPerformed);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("Return Book:");

        RB_Btn1.setText("jButton1");
        RB_Btn1.addActionListener(this::RB_Btn1ActionPerformed);

        RB_Btn2.setText("jButton2");
        RB_Btn2.addActionListener(this::RB_Btn2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(RB_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(RB_Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RB_Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RB_Combo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB_Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RB_Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RB_Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_Btn1ActionPerformed
    // Mark as submitted and close when OK button is clicked :O
    submitted = true;
    dispose();
    }//GEN-LAST:event_RB_Btn1ActionPerformed

    private void RB_Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_Btn2ActionPerformed
    // Closes the dialog when Cancel button is pressed
    dispose();  
    }//GEN-LAST:event_RB_Btn2ActionPerformed

    private void RB_ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_ComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_ComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ReturnBook dialog = new ReturnBook(new javax.swing.JFrame(), true, new java.util.ArrayList<>());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RB_Btn1;
    private javax.swing.JButton RB_Btn2;
    private javax.swing.JComboBox<String> RB_Combo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
