// imports
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author 
 */
public class AddBook extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddBook.class.getName());

    /**
     * Creates new form AddBook
     */
    public AddBook(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookIDText = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TitleText = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AuthorText = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ISBNText = new javax.swing.JTextArea();
        AB_OK = new javax.swing.JButton();
        AB_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Book ID");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("Book ID:");

        BookIDText.setColumns(20);
        BookIDText.setRows(5);
        jScrollPane1.setViewportView(BookIDText);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel2.setText("Title:");

        TitleText.setColumns(20);
        TitleText.setRows(5);
        jScrollPane2.setViewportView(TitleText);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel3.setText("Author:");

        AuthorText.setColumns(20);
        AuthorText.setRows(5);
        jScrollPane3.setViewportView(AuthorText);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel4.setText("ISBN:");

        ISBNText.setColumns(20);
        ISBNText.setRows(5);
        jScrollPane4.setViewportView(ISBNText);

        AB_OK.setText("OK");
        AB_OK.addActionListener(this::AB_OKActionPerformed);

        AB_Cancel.setText("Cancel");
        AB_Cancel.addActionListener(this::AB_CancelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(AB_OK)
                        .addGap(47, 47, 47)
                        .addComponent(AB_Cancel)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AB_OK)
                    .addComponent(AB_Cancel))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AB_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AB_OKActionPerformed
    // Check all fields are filled, or else user wont be able to continue
    if (BookIDText.getText().isBlank() ||
        TitleText.getText().isBlank() ||
        AuthorText.getText().isBlank() ||
        ISBNText.getText().isBlank()) {
        
        JOptionPane.showMessageDialog(this, "Please fill in all fields!!!!");
        return; // stops here, keeps the form open, the user can then exit with the cancel button ;D
    }
    
    // If the user enters anything other than an int into the Member ID or ISBN ID field
    // a message appears telling them to input integer values instead
    // using the try catch method 

    try {
        int ISBNID = Integer.parseInt(ISBNText.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid ISBN ID: Please use only integers, and try again.");
        return; // keeps the form open
    } 

        submitted = true;
        dispose();
        
    try {
        int BookID = Integer.parseInt(BookIDText.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid Book ID: Please use only integers, and try again.");
        return; // keeps the form open
    } 

        submitted = true;
        dispose();   
    }//GEN-LAST:event_AB_OKActionPerformed

    private void AB_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AB_CancelActionPerformed
    // Exits the AddBook form
        dispose();
    }//GEN-LAST:event_AB_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddBook dialog = new AddBook(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // adding getters to extract data user inputs into the text fields 
    // when ok button clicked 

    public int getBookID() {
        return Integer.parseInt(BookIDText.getText());
    }

    public String getTitle() {
        return TitleText.getText();
    }

    public String getAuthor() {  
        return AuthorText.getText();
    }

    public int getISBN() {
        return Integer.parseInt(ISBNText.getText());
    }        
    
    // Sets submit button to true
    private boolean submitted = false;

    public boolean wasSubmitted() { return submitted; }

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {
        submitted = true;
        dispose();
    }        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AB_Cancel;
    private javax.swing.JButton AB_OK;
    private javax.swing.JTextArea AuthorText;
    private javax.swing.JTextArea BookIDText;
    private javax.swing.JTextArea ISBNText;
    private javax.swing.JTextArea TitleText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
